services:
  - type: web
    name: mlproject-ml-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mlproject.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mlproject.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: DEBUG
        value: False
